### ISSUE TITLE
meanio-circles error aggregateAsset is not a function

### ISSUE THREAD

**Issue by pradeepnama2009** [rjVapes/meanio-circles#1]
I:\Mean\medical\node_modules\q\q.js:155
                throw e;
                ^

TypeError: Circles.aggregateAsset is not a function
    at I:\Mean\medical\node_modules\meanio-circles\app.js:22:11

Please help

**Comment by jwebbdev** [comment]
Yeah, this is being fixed in a PR in linnovate/meanio-circles where this package is now being maintained.  You can open an issue there if you want, but once the PR is merged it should be fine.  If your mean installation is referencing my packages I'd suggest replacing all rjVapes with linnovate.
